# Multi-stage build producing a minimal production image (Next.js standalone output).
# Prisma's query engine is platform-specific, so `prisma generate` must run inside this
# container (not copied from the host) — that's why it happens in the builder stage below.

FROM node:20-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:20-slim AS builder
WORKDIR /app
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV DATABASE_URL="file:./dev.db"
RUN npx prisma generate
RUN npm run build

FROM node:20-slim AS runner
WORKDIR /app
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
ENV NODE_ENV=production
RUN groupadd --system --gid 1001 nodejs && useradd --system --uid 1001 --gid nodejs nextjs

# The Prisma CLI isn't traced into the standalone bundle (it's invoked via a separate process,
# not imported by app code) — installed explicitly, pinned to match the schema/client version,
# so migrations can be applied on container start without a network fetch at runtime.
RUN npm install --no-save prisma@6.19.3

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder /app/prisma ./prisma
COPY docker-entrypoint.sh ./
RUN chmod +x docker-entrypoint.sh && chown nextjs:nodejs docker-entrypoint.sh

# /data is where docker-compose.yml mounts the SQLite volume — created with the right ownership
# here so a fresh named volume (which Docker mounts as an empty, root-owned dir) is actually
# writable by the non-root `nextjs` user once the volume is attached at container start.
RUN mkdir -p /data && chown nextjs:nodejs /data

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# server.js is generated by Next's standalone output — the entrypoint applies pending migrations
# first, then execs it directly (no `next start`).
ENTRYPOINT ["./docker-entrypoint.sh"]
