# Multi-stage build producing a minimal production image (Next.js standalone output).
# Prisma's query engine is platform-specific, so `prisma generate` must run inside this
# container (not copied from the host) — that's why it happens in the builder stage below.

FROM node:20-slim AS deps
WORKDIR /app
# better-sqlite3 (the Prisma driver adapter's native binding) has no prebuilt binary for every
# platform this image might be built on, so it falls back to compiling from source via node-gyp.
RUN apt-get update -y && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*
COPY package.json package-lock.json ./
# npm ci's postinstall hook runs `prisma generate`, which needs the schema + config present -
# copied here (ahead of the full `COPY . .` in the builder stage below) so this layer still
# only invalidates on dependency or schema changes, not on every source file edit.
COPY prisma/schema.prisma ./prisma/schema.prisma
COPY prisma.config.ts ./
RUN npm ci

FROM node:20-slim AS builder
WORKDIR /app
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV DATABASE_URL="file:./prisma/dev.db"
RUN npx prisma generate
RUN npm run build

FROM node:20-slim AS runner
WORKDIR /app
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
ENV NODE_ENV=production
RUN groupadd --system --gid 1001 nodejs && useradd --system --uid 1001 --gid nodejs nextjs

# The Prisma CLI isn't traced into the standalone bundle (it's invoked via a separate process,
# not imported by app code) — installed explicitly, pinned to match the schema/client version,
# so migrations can be applied on container start without a network fetch at runtime. dotenv is
# a no-op here (env vars come from docker-compose, not a .env file) but prisma.config.ts imports
# it unconditionally, so it still has to be resolvable.
RUN npm install --no-save prisma@7.8.0 dotenv@17.4.2

# Full node_modules (incl. devDependencies like tsx) so the one-time `npx prisma db seed` can be
# run directly in this image later - the standalone output below only bundles what the Next.js
# server itself traces as used, which doesn't cover an ad-hoc script invoked outside the app.
COPY --from=deps /app/node_modules ./node_modules

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts
COPY --from=builder /app/src/generated ./src/generated
COPY --from=builder /app/src/lib/crypto.ts ./src/lib/crypto.ts
COPY docker-entrypoint.sh ./
RUN chmod +x docker-entrypoint.sh && chown nextjs:nodejs docker-entrypoint.sh

# /data is where the SQLite volume mounts. Chowning it here only affects this image layer —
# Docker Compose named volumes copy that ownership in on first mount, but platform-provisioned
# volumes (e.g. Railway) are independent block storage mounted root-owned regardless of what the
# image had at that path. Running as root sidesteps the mismatch instead of fighting it.
RUN mkdir -p /data

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# server.js is generated by Next's standalone output — the entrypoint applies pending migrations
# first, then execs it directly (no `next start`).
ENTRYPOINT ["./docker-entrypoint.sh"]
